apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  labels:
    app: payment-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: omni-commerce/payment-service:latest
          ports:
            - containerPort: 3003
          envFrom:
            - configMapRef:
                name: payment-service-config
            - secretRef:
                name: payment-service-secret
          resources:
            requests:
              memory: '128Mi'
              cpu: '100m'
            limits:
              memory: '512Mi'
              cpu: '500m'
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  selector:
    app: payment-service
  type: ClusterIP
  ports:
    - port: 3003
      targetPort: 3003
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-service-config
data:
  PORT: '3003'
  NODE_ENV: production
  DB_HOST: postgres-payment
  DB_PORT: '5432'
  DB_USER: postgres
  DB_NAME: payment_db
  KAFKA_BROKER: kafka:29092
---
apiVersion: v1
kind: Secret
metadata:
  name: payment-service-secret
type: Opaque
stringData:
  DB_PASSWORD: postgres
