apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-order
  labels:
    app: postgres-order
spec:
  serviceName: postgres-order
  replicas: 1
  selector:
    matchLabels:
      app: postgres-order
  template:
    metadata:
      labels:
        app: postgres-order
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: order_db
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-order-secret
                  key: POSTGRES_PASSWORD
          readinessProbe:
            exec:
              command: ['pg_isready', '-U', 'postgres', '-d', 'order_db']
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            exec:
              command: ['pg_isready', '-U', 'postgres', '-d', 'order_db']
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            requests:
              memory: '128Mi'
              cpu: '100m'
            limits:
              memory: '512Mi'
              cpu: '500m'
          volumeMounts:
            - name: postgres-order-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-order-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-order
spec:
  selector:
    app: postgres-order
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-order-secret
type: Opaque
stringData:
  POSTGRES_PASSWORD: postgres
