apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  labels:
    app: product-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: omni-commerce/product-service:latest
          ports:
            - containerPort: 3001
          envFrom:
            - configMapRef:
                name: product-service-config
            - secretRef:
                name: product-service-secret
          resources:
            requests:
              memory: '128Mi'
              cpu: '100m'
            limits:
              memory: '512Mi'
              cpu: '500m'
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  selector:
    app: product-service
  type: ClusterIP
  ports:
    - port: 3001
      targetPort: 3001
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: product-service-config
data:
  PORT: '3001'
  NODE_ENV: production
  DB_HOST: postgres-product
  DB_PORT: '5432'
  DB_USER: postgres
  DB_NAME: product_db
  REDIS_HOST: redis
  REDIS_PORT: '6379'
  KAFKA_BROKER: kafka:29092
---
apiVersion: v1
kind: Secret
metadata:
  name: product-service-secret
type: Opaque
stringData:
  DB_PASSWORD: postgres
