filebeat.inputs:
  - type: container
    paths:
      - /var/lib/docker/containers/*/*.log
    processors:
      - add_docker_metadata:
          host: 'unix:///var/run/docker.sock'
      - decode_json_fields:
          fields: ['message']
          target: ''
          overwrite_keys: true

processors:
  - drop_fields:
      fields: ['agent', 'host', 'input', 'log', 'stream', 'ecs']
      ignore_missing: true

output.elasticsearch:
  hosts: ['http://elasticsearch:9200']
  index: 'omni-logs-%{+yyyy.MM.dd}'

setup.ilm.enabled: false
setup.template.name: 'omni-logs'
setup.template.pattern: 'omni-logs-*'
